name: 'Lint VBA'
description: 'Lint VBA source code.'
branding:
  icon: "sun"
  color: "red"
inputs:
  path:
    description: 'Path to source files.'
    default: "."
runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install antlr4-tools 1>/dev/null
        wget -q https://raw.githubusercontent.com/Beakerboy/VBA_Tokenizer/ANTLR/vba.g4
        antlr4-parse 1>/dev/null
      shell: bash
    - run: |
        ${{ inputs.path }} = "${{ github.workspace }}/${{ inputs.path }}"
        for x in $(find ${{ inputs.path }} \( -name "*.cls" -o -name "*.bas" -o -name "*.frm" \))
        do
          foo=$(antlr4-parse vba.g4 startRule $x)
          echo "$x"
          if [[ $foo != "" ]];
          then echo $foo 1>&2;
            exit 1;
          fi
        done
      shell: bash
